// It is a good idea to have one file where all the action of the program is declared to avoid similar action names

// Register View actions
export const CORRECT_USERNAME_REGISTER = 'CORRECT_USERNAME';
export const CORRECT_PASSWORD_REGISTER = 'CORRECT_PASSWORD';
export const CORRECT_CONFIRM_PASSWORD = 'CORRECT_CONFIRM_PASSWORD';
export const CORRECT_EMAIL = 'CORRECT_EMAIL';
export const CORRECT_FIRST_NAME = 'CORRECT_FIRST_NAME';
export const CORRECT_LAST_NAME = 'CORRECT_LAST_NAME';
export const CORRECT_PHONE = 'CORRECT_PHONE';
export const CORRECT_DOB = 'CORRECT_DOB';
export const NO_USERNAME_REGISTER = 'NO_USERNAME_REGISTER';
export const USERNAME_EXISTS = 'USERNAME_EXISTS';
export const WEAK_PASSWORD = 'WEAK_PASSWORD';
export const NO_PASSWORD_REGISTER = 'NO_PASSWORD_REGISTER';
export const INCORRECT_CONFIRM_PASSWORD = 'INCORRECT_CONFIRM_PASSWORD';
export const NO_CONFIRM_PASSWORD = 'NO_CONFIRM_PASSWORD';
export const INVALID_EMAIL = 'INVALID_EMAIL';
export const NO_EMAIL = 'NO_EMAIL';
export const EMAIL_EXISTS = 'EMAIL_EXISTS';
export const NO_FIRST_NAME = 'NO_FIRST_NAME';
export const NO_LAST_NAME = 'NO_LAST_NAME';
export const INVALID_PHONE = 'INVALID_PHONE';
export const NO_PHONE = 'NO_PHONE';
export const NO_DOB = 'NO_DOB';
export const SET_USERNAME_REGISTER = 'SET_USERNAME_REGISTER';
export const SET_PASSWORD_REGISTER = 'SET_PASSWORD_REGISTER';
export const SET_CONFIRM_PASSWORD = 'SET_CONFIRM_PASSWORD';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_FIRST_NAME = 'SET_FIRST_NAME';
export const SET_LAST_NAME = 'SET_LAST_NAME';
export const SET_PHONE = 'SET_PHONE';
export const SET_DOB = 'SET_DOB';
export const CLEAR_REGISTER_UI_CHANGES = "CLEAR_REGISTER_UI_CHANGES";
export const SAVE_REGISTER_FORM = 'SAVE_REGISTER_FORM';
export const CLEAR_REGISTER_FORM = 'CLEAR_REGISTER_FORM';
export const REGISTER_LOADING_ON = 'REGISTER_LOADING_ON';
export const REGISTER_LOADING_OFF = 'REGISTER_LOADING_OFF';

// Login View actions
export const LOGIN_LOADING_ON = 'LOGIN_LOADING_ON';
export const LOGIN_LOADING_OFF = 'LOGIN_LOADING_OFF';
export const SET_USERNAME_LOGIN = 'SET_USERNAME_LOGIN';
export const SET_PASSWORD_LOGIN = 'SET_PASSWORD_LOGIN';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const CLEAR_USERNAME_RED_BORDER = 'CLEAR_USERNAME_RED_BORDER';
export const CLEAR_PASSWORD_RED_BORDER = 'CLEAR_PASSWORD_RED_BORDER';
export const NO_USERNAME_LOGIN = 'NO_USERNAME_LOGIN';
export const NO_PASSWORD_LOGIN = 'NO_PASSWORD_LOGIN';
export const CLEAR_LOGIN_FORM = 'CLEAR_LOGIN_FORM';
export const CLEAR_LOGIN_UI_CHANGES = 'CLEAR_LOGIN_UI_CHANGES';
export const AUTHENTICATION_COMPLETE = 'AUTHENTICATION_COMPLETE';
