// contains the reducer for react navigator
import { NavigationActions } from 'react-navigation';
import { Navigator } from '../navigator/Navigator';

// The initial state of the Navigator is taken, this state is actually the entire react navigation stack.
const initialState = Navigator.router.getStateForAction(NavigationActions.init())

export default (state = initialState, action) => {
    // Gets the next state of the navigator by passing in the action generated by the navigator component.
    // The function getStateForAction generates an action for a given state and returns the next state for that action and state.
    const nextState = Navigator.router.getStateForAction(action, state);

    // return nextState if it its not null, if it is null then return the state
    return nextState || state;
}
